@routeName = contact-appointment-reason
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "contact_reason_id": 344,
        "contact_appointment_id": 4234
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
    "contact_reason_id": 43543,
        "contact_appointment_id": 34534
}
