@routeName = customer-variant-customer
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "customer_id": "123",
        "variant_id": "1232",
        "variant_value_id": "5342"
}

###
POST {{host}}{{routeName}}/update/2 HTTP/1.1
content-type: application/json

{
    "customer_id": "232",
        "variant_id": "645",
        "variant_value_id": "8676"
}
