@routeName = crm-contact-number
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "operator": "banglalink",
        "details": "somethings"
}

###
POST {{host}}{{routeName}}/update/2 HTTP/1.1
content-type: application/json

{
         "operator": "airtel",
        "details": "somethings"
}
