@routeName = user-work

GET http://localhost:8082/{{routeName}} HTTP/1.1

###
GET http://localhost:8082/{{routeName}}/details/4 HTTP/1.1


###
DELETE http://localhost:8082/{{routeName}}/delete/2 HTTP/1.1

###
POST http://localhost:8082/{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "title": "teaching"
}

###
POST http://localhost:8082/{{routeName}}/update/4 HTTP/1.1
content-type: application/json

{
    "title": "teaching"
}
