@routeName = customer-variant-value
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/1 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/2 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "variant_id": 33,
        "title": "Tarek don"
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
    "variant_id": 55,
        "title": "Momin don"
}
