@routeName = customer
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/1 HTTP/1.1

###
GET  http://localhost:8082/api/test-auth HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJpYXQiOjE3MDk5NzQ0NTl9.ElpIQYfRnQarw9rUkbwuC4l3a7DoIjt8KILqWAtI9Cs

###
GET {{host}}{{routeName}}/variant/details/1 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/8 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "uuid": "123",
        "full_name": "Tarek don",
        "email": "tarek@gamil.com",
        "contact_number": "01777777777",
        "address": "mirpur"
}

###
POST {{host}}{{routeName}}/update/2 HTTP/1.1
content-type: application/json

{
        "uuid": "321",
        "full_name": "Ehsan sir",
        "email": "ehsan@gamil.com",
        "contact_number": "018777775",
        "address": "shonir akhrha"
}
