@routeName = customer
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/1 HTTP/1.1


###
GET {{host}}{{routeName}}/variant/details/1 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/8 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "uuid": "123",
        "full_name": "Tarek don",
        "email": "tarek@gamil.com",
        "contact_number": "01777777777",
        "address": "mirpur"
}

###
POST {{host}}{{routeName}}/update/2 HTTP/1.1
content-type: application/json

{
        "uuid": "321",
        "full_name": "Ehsan sir",
        "email": "ehsan@gamil.com",
        "contact_number": "018777775",
        "address": "shonir akhrha"
}
