@routeName = contact-appointment
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "contact_number_id": 222,
        "customer_id": "432",
        "date": "2022-10-12",
        "contact_type": "This is very informative",
        "note": "This is very informative",
        "creator": 324
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
        "contact_number_id": 654,
        "customer_id": "432",
        "date": "2022-10-12",
        "contact_type": "This is very informative",
        "note": "This is very informative",
        "creator": 324
}
