@routeName = lead
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/3 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "customer_id": 2,
        "lead_status": "pending",
        "lead_source": "facebook",
        "assigned_to": 3,
        "qualification_notes": "Needs analysis",
        "follow_up_date": "2022-10-12"
}

###
POST {{host}}{{routeName}}/update/3 HTTP/1.1
content-type: application/json

{
        "customer_group_id": "444",
        "customer_id": "44"
}
