@routeName = report
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/1 HTTP/1.1

###
GET  http://localhost:8082/api/test-auth HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

###
GET {{host}}{{routeName}}/per-month HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

###
GET {{host}}{{routeName}}/all-customer HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

###
GET {{host}}{{routeName}}/pending-customer HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

###
POST {{host}}{{routeName}}/admitted-customer HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

{
        "month": "2022-11-22"
}

###
GET {{host}}{{routeName}}/upcoming-contact-list HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

###
POST {{host}}{{routeName}}/reject-customer-per-month HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

{
        "month": "2022-10-12"
}

###
GET {{host}}{{routeName}}/interested-customer HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw


###
DELETE {{host}}{{routeName}}/delete/8 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InlhbWluIiwicm9sZSI6ImVtcGxveWVlIiwiaWQiOjEyLCJlbWFpbCI6Im1tbUBnbWFpbC5jb20iLCJ0b2tlbl9zYWx0IjoiMjYwYmE2ZDVlMTlmZDAyMDM5MTEiLCJpYXQiOjE3MTA4MjAxNjN9.phwbKA21KGKLXRMXSRRGMOU3dL37aeNCZvMrdwzR4Uw

{
        "uuid": "123",
        "full_name": "momin donn",
        "email": "tarek@gamil.com",
        "contact_number": "01777777777",
        "address": "mirpur"
}

###
POST {{host}}{{routeName}}/update/2 HTTP/1.1
content-type: application/json

{
        "uuid": "321",
        "full_name": "Ehsan sir",
        "email": "ehsan@gamil.com",
        "contact_number": "018777775",
        "address": "shonir akhrha"
}
