@routeName = user

GET http://localhost:8082/{{routeName}} HTTP/1.1

###
GET http://localhost:8082/{{routeName}}/details/2 HTTP/1.1


###
GET http://localhost:8082/{{routeName}}/full-details/2 HTTP/1.1


###
DELETE http://localhost:8082/{{routeName}}/delete/4 HTTP/1.1

###
POST http://localhost:8082/{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "user_name": "alif",
        "password": "1234",
        "email": "alif@gmail.com",
        "role": "admin"
}

###
POST http://localhost:8082/{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
        "user_name": "sagir",
        "password": "1234",
        "email": "sagir@gmail.com",
        "role": "student"
}
