@routeName = task

GET http://localhost:8082/{{routeName}} HTTP/1.1

###
GET http://localhost:8082/{{routeName}}/details/2 HTTP/1.1


###
DELETE http://localhost:8082/{{routeName}}/delete/4 HTTP/1.1

###
POST http://localhost:8082/{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "title": "user onboarding",
        "description": "Create a seamless onboarding process",
        "end_time": "2024-10-12"
}

###
POST http://localhost:8082/{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
        "title": "data inport",
        "description": "Develop a feature to import existing customer",
        "end_time": "2024-10-12"
}
