@routeName = task
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/1 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "title": "user onboarding",
        "description": "Create a seamless onboarding process",
        "end_time": "2024-10-12"
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
        "title": "data inport",
        "description": "Develop a feature to import existing customer",
        "end_time": "2024-10-12"
}
