GET http://localhost:8082/customer-support-ticket HTTP/1.1

###
GET http://localhost:8082/product/details/4 HTTP/1.1


###
DELETE http://localhost:8082/customer-support-ticket/delete/2 HTTP/1.1

###
POST http://localhost:8082/customer-support-ticket/store HTTP/1.1
content-type: application/json

{
        "customer_id": 123,
        "ticket_uuid": "11",
        "subject": "English",
        "description": "This is good",
        "priority": "low"
}

###
POST http://localhost:8082/customer-support-ticket/update/3 HTTP/1.1
content-type: application/json

{
    "customer_id": 111,
        "ticket_uuid": "22",
        "subject": "Web Development",
        "description": "This is good Course",
        "priority": "high"
}
