GET http://localhost:8082/product HTTP/1.1

###
GET http://localhost:8082/product/details/4 HTTP/1.1


###
DELETE http://localhost:8082/product/delete/5 HTTP/1.1

###
POST http://localhost:8082/customer-support-ticket/store HTTP/1.1
content-type: application/json

{
        "customer_id": 123,
        "ticket_uuid": "11",
        "subject": "English",
        "description": "This is good",
        "priority": "low"
}

###
POST http://localhost:8082/product/update/4 HTTP/1.1
content-type: application/json

{
    "title": "Iphone15 pro max",
    "price": 1000,
    "description": "This is very good",
    "published" : false
}
