@routeName = task-variant-task
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "task_id": 3,
        "variant_id": 2,
        "task_variant_value_id": 2
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
     "task_id": 2,
        "variant_id": 2,
        "task_variant_value_id": 2
}
