@routeName = task-variant-task

GET http://localhost:8082/{{routeName}} HTTP/1.1

###
GET http://localhost:8082/{{routeName}}/details/2 HTTP/1.1


###
DELETE http://localhost:8082/{{routeName}}/delete/4 HTTP/1.1

###
POST http://localhost:8082/{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "task_id": 3,
        "variant_id": 2,
        "task_variant_value_id": 2
}

###
POST http://localhost:8082/{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
     "task_id": 2,
        "variant_id": 2,
        "task_variant_value_id": 2
}
