@routeName = customer-contact-number
@host = http://localhost:8082/api/

GET {{host}}{{routeName}} HTTP/1.1

###
GET {{host}}{{routeName}}/details/2 HTTP/1.1


###
DELETE {{host}}{{routeName}}/delete/4 HTTP/1.1

###
POST {{host}}{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "customer_id": 222,
        "operator": "Tarek don",
        "details": "This is very informative"
}

###
POST {{host}}{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
        "customer_id": 444,
        "operator": "Robi",
        "details": "This is very informative"
}
