@routeName = user-info

GET http://localhost:8082/{{routeName}} HTTP/1.1

###
GET http://localhost:8082/{{routeName}}/details/2 HTTP/1.1


###
DELETE http://localhost:8082/{{routeName}}/delete/4 HTTP/1.1

###
POST http://localhost:8082/{{routeName}}/store HTTP/1.1
content-type: application/json

{
        "user_id": 2,
        "first_name": "alif",
        "last_name": "sagir",
        "designation": "student",
        "date_of_birth": "2022-10-12",
        "phone_number": "01778639643"
}

###
POST http://localhost:8082/{{routeName}}/update/1 HTTP/1.1
content-type: application/json

{
        "user_id": 1,
        "first_name": "abdullah",
        "last_name": "sadik",
        "designation": "student",
        "date_of_birth": "2022-10-12",
        "phone_number": "01798398934"
}
